baseURL = 'https://asymptote-4k2.pages.dev/'
languageCode = 'en-us'
title = 'Asymptote'
theme = 'PaperMod'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
  ShowPostsOnHomePage = true
